services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: requirements/nginx/
    image: nginx
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - nkeyani_net
    ports:
      - "443:443"
    restart: always

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - nkeyani_net
    env_file:
      - .env
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - nkeyani_net
    env_file:
      - .env
    restart: always

  #bonus
  static_page:
    container_name: static_page
    build: requirements/bonus/static_page
    image: static_page
    restart: always
    networks:
      - nkeyani_net
    ports:
      - "4343:4343"

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      device: "/home/${USER}/data/wordpress"
      o: bind
      type: none

  mariadb_data:
    driver: local
    driver_opts:
      device: "/home/${USER}/data/mariadb"
      o: bind
      type: none

networks:
  nkeyani_net:
    name: nkeyani_net
    driver: bridge
